# Generated by Django 6.0.4 on 2026-04-12 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('ELEVES', 'Élèves'), ('RESULTATS', 'Résultats')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('stats', models.JSONField()),
                ('errors', models.JSONField(default=list)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
