# Generated by Django 6.0.4 on 2026-04-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('fiche', models.IntegerField(primary_key=True, serialize=False)),
                ('permanent_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('current_group', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
