# Generated by Django 6.0.4 on 2026-04-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(db_index=True, max_length=20)),
                ('course_description', models.CharField(max_length=255)),
                ('course_group', models.CharField(max_length=10)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('step_1_grade', models.IntegerField(blank=True, null=True)),
                ('step_2_grade', models.IntegerField(blank=True, null=True)),
                ('final_grade', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'course_code')},
            },
        ),
    ]
