# Generated by Django 6.0.4 on 2026-04-09 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('students', '0002_academicresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicresult',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school.courseoffering'),
        ),
    ]
