# Generated by Django 6.0.4 on 2026-04-09 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_is_active_courseoffering_is_active_and_more'),
        ('students', '0003_academicresult_offering'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicresult',
            unique_together={('student', 'offering')},
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school.courseoffering'),
        ),
        migrations.RemoveField(
            model_name='academicresult',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='academicresult',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='academicresult',
            name='course_group',
        ),
        migrations.RemoveField(
            model_name='academicresult',
            name='teacher_name',
        ),
    ]
