# Generated by Django 6.0.4 on 2026-04-09 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_is_active_courseoffering_is_active_and_more'),
        ('students', '0004_alter_academicresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicresult',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school.courseoffering'),
        ),
    ]
