# Generated by Django 6.0.4 on 2026-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_academicresult_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicresult',
            name='academic_year',
            field=models.CharField(db_index=True, default='2023-2024', max_length=9),
        ),
    ]
