# Generated by Django 6.0.4 on 2026-04-09 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_add_pedagogical_metadata'),
        ('students', '0006_academicresult_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicresult',
            name='academic_year',
            field=models.CharField(db_index=True, default='2025-2026', max_length=9),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school.courseoffering'),
        ),
    ]
