# Generated by Django 6.0.4 on 2026-04-09 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_cohort'),
        ('students', '0007_add_pedagogical_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPromotionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(db_index=True, max_length=9)),
                ('override_type', models.CharField(choices=[('FORCE_PASS', 'Passage Forcé'), ('FORCE_RETAKE', 'Reprise Forcée'), ('TRANSFER_IFP', 'Transfert IFP'), ('TRANSFER_DIM', 'Transfert DIM')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'academic_year')},
            },
        ),
    ]
