# Generated by Django 6.0.4 on 2026-04-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_course_level'),
        ('students', '0009_summerschoolenrollment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicresult',
            index=models.Index(fields=['student', 'academic_year'], name='students_ac_student_18473d_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresult',
            index=models.Index(fields=['academic_year'], name='students_ac_academi_5d0174_idx'),
        ),
    ]
