# Generated by Django 6.0.4 on 2026-05-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_academicresult_students_ac_student_18473d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(db_index=True, max_length=9)),
                ('workflow_state', models.CharField(blank=True, choices=[('IFP_CANDIDATE_REVIEW', 'Révision des candidats IFP'), ('REGULAR_REVIEW_PENDING', 'Révision régulière en attente'), ('READY_FOR_FINALIZATION', 'Prêt pour finalisation')], max_length=50, null=True)),
                ('final_april_state', models.CharField(blank=True, choices=[('APRIL_FINAL_PROMOTE_REGULAR', 'Promotion régulière'), ('APRIL_FINAL_PROMOTE_WITH_SUMMER', "Promotion avec cours d'été"), ('APRIL_FINAL_HOLDBACK', 'Doublement'), ('APRIL_FINAL_IFP_N', 'IFP N'), ('APRIL_FINAL_IFP_N_MINUS_1', 'IFP N-1')], max_length=50, null=True)),
                ('vetting_status', models.CharField(choices=[('AUTO_VETTED', 'Validé automatiquement'), ('REQUIRES_REVIEW', 'Nécessite une révision'), ('MANUALLY_VETTED', 'Validé manuellement')], default='REQUIRES_REVIEW', max_length=50)),
                ('ifp_target', models.CharField(blank=True, max_length=10, null=True)),
                ('reason_codes', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_academic_year')],
            },
        ),
    ]
