# Generated by Django 6.0.4 on 2026-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_is_active_courseoffering_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='academic_year',
            field=models.CharField(db_index=True, default='2023-2024', max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'group_number', 'academic_year')},
        ),
    ]
