# Generated by Django 6.0.4 on 2026-04-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_courseoffering_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0, help_text='Nombre de crédits associés au cours'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_core_or_sanctioned',
            field=models.BooleanField(default=False, help_text='Vrai pour les matières de base bloquantes comme le français ou les mathématiques, ou les matières sanctionnées par le MEQ'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(blank=True, help_text='Année du secondaire (1 à 5)', null=True),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='academic_year',
            field=models.CharField(db_index=True, default='2025-2026', max_length=9),
        ),
    ]
