# Generated by Django 6.0.4 on 2026-04-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_add_pedagogical_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='code',
            new_name='local_code',
        ),
        migrations.AddField(
            model_name='course',
            name='meq_code',
            field=models.CharField(blank=True, help_text='Code officiel du Ministère (MEQ)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='periods',
            field=models.IntegerField(default=0, help_text="Nombre de périodes dans l'horaire"),
        ),
    ]
