# Generated by Django 6.0.4 on 2026-04-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_code_course_local_code_course_meq_code_and_more'),
        ('students', '0007_add_pedagogical_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cohort_type', models.CharField(choices=[('ZENITH', 'Zénith'), ('IFP', 'IFP'), ('DIM', 'DIM'), ('ACCUEIL', 'Accueil'), ('PARCOURS', 'Parcours')], max_length=20)),
                ('academic_year', models.CharField(db_index=True, max_length=9)),
                ('min_capacity', models.IntegerField(default=15)),
                ('max_capacity', models.IntegerField(default=32)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('students', models.ManyToManyField(blank=True, related_name='cohorts', to='students.student')),
            ],
            options={
                'unique_together': {('name', 'academic_year')},
            },
        ),
    ]
