# Generated by Django 6.0.4 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_cohort"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeqReference",
            fields=[
                ("meq_code", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("credits", models.IntegerField(default=0)),
            ],
        ),
    ]

