# Generated by Django 6.0.4 on 2026-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_course_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(blank=True, help_text='Année du secondaire (0=Accueil, 1 à 5)', null=True),
        ),
    ]
